### ISSUE TITLE
Improve contact section and page

### ISSUE THREAD

**Issue by alexisvisco** [asvf-montagne/client#142]
Français: 

La page de contact doit être affiné pour indiquer que l'heure à laquelle c'est ouvert c'est pour l'astreinte et pas les séances. 
Il faudrait aussi que quand on clique sur les boutons ça ouvre respectivement, le mail, le téléphone et maps.

**Comment by antoineaudrain** [comment]
tu peut me donner les url pour rediriger respectivement, le mail, le téléphone et maps stp?

**Comment by alexisvisco** [comment]
maps: https://www.google.fr/maps/dir/45.606895,5.155242/'45.614337,5.173802'/@45.6124801,5.1595849,6556m/data=!3m1!1e3!4m7!4m6!1m1!4e1!1m3!2m2!1d5.1738042!2d45.6143376?hl=fr

mail: il faut utiliser mailto et le mail qu'il y a dans contact (https://developer.mozilla.org/fr/docs/Web/Guide/HTML/Liens_email)

tel: <a href="tel:+33500000000">Link text</a> ; avec le numéro de tel
